functions:
  post_get: ${file(lambda_functions/post/functions.yml):post_get}
  post_create: ${file(lambda_functions/post/functions.yml):post_create}
  post_list: ${file(lambda_functions/post/functions.yml):post_list}
  # post_delete: ${file(lambda_functions/post/functions.yml):post_delete}
  # post_update: ${file(lambda_functions/post/functions.yml):post_update}
  auth_post: ${file(lambda_functions/auth/functions.yml):auth_post}
  auth_authorizer: ${file(lambda_functions/auth/functions.yml):auth_authorizer}
  trigger_dynamo_to_es: ${file(lambda_functions/triggers/functions.yml):trigger_dynamo_to_es}
